<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MeitalDaniel-PC" name="TestCases.Login_Test" tests="6" failures="1" timestamp="2020-06-12T08:55:13 IDT" time="30.719" errors="0">
  <testcase name="T01_invalidLoginAttempts" time="4.239" classname="TestCases.Login_Test"/>
  <system-out/>
  <testcase name="T01_invalidLoginAttempts" time="4.310" classname="TestCases.Login_Test"/>
  <system-out/>
  <testcase name="T01_invalidLoginAttempts" time="4.265" classname="TestCases.Login_Test"/>
  <system-out/>
  <testcase name="T01_invalidLoginAttempts" time="6.276" classname="TestCases.Login_Test"/>
  <system-out/>
  <testcase name="T01_invalidLoginAttempts" time="4.307" classname="TestCases.Login_Test"/>
  <system-out/>
  <testcase name="T01_successfulLogin" time="7.322" classname="TestCases.Login_Test">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	expected [Productssssss] but found [Products]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
expected [Productssssss] but found [Products]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:47)
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:31)
at TestCases.Login_Test.T01_successfulLogin(Login_Test.java:57)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:134)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:597)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:816)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.util.ArrayList.forEach(Unknown Source)
at org.testng.TestRunner.privateRun(TestRunner.java:766)
at org.testng.TestRunner.run(TestRunner.java:587)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1109)
at org.testng.TestNG.runSuites(TestNG.java:1039)
at org.testng.TestNG.run(TestNG.java:1007)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- T01_successfulLogin -->
  <system-out/>
</testsuite> <!-- TestCases.Login_Test -->
